### PR TITLE
Fix "... docker-compose.yaml is invalid" error

### PR DESCRIPTION
**Pull request by guyzyl**
Fixes the following error:
```bash
ERROR: The Compose file './docker-compose.yaml' is invalid because:
services.app.depends_on contains an invalid type, it should be an array
services.nginx.depends_on contains an invalid type, it should be an array
services.postgres.volumes contains an invalid type, it should be a string
```

### CODE REVIEW

**Comment by gregelin** [comment]
Thanks @guyzyl . Taking a list at your PR!

**Comment by gregelin** [comment]
@guyzyl Looks like you are running a newer version of Docker Compose. My CTO thinks there's a different better fix to "modify the entrypoint.sh files to wait for sockets become available." He's going to work on this today.

**Comment by guyzyl** [comment]
@gregelin sure thing. You can find Docker's recommendation on how to implement waiting for a container to be ready [here](https://docs.docker.com/compose/startup-order/).
I'm leaving this PR open ATM, you can close it once a different fix is merged.

**Comment by alexanderward** [comment]
@guyzyl Thank you for reaching out.  This code was originally written w/ docker-compose v1 in mind.  Your PR only addresses some of the issues involved in the conversion to v2.  I have created a PR that addresses all the other pieces.  Feel free to check out what changed: https://github.com/GovReady/govready-deployments/pull/26

**Pull request closed without merging**
